#!/bin/sh
set -eu
hypr_dir="${XDG_CONFIG_HOME:-$HOME/.config}/hypr"
root_file="$hypr_dir/hyprland.lua"
look_file="$hypr_dir/user/look.lua"
stamp="$(date +%Y%m%d-%H%M%S)"
[ -f "$root_file" ] || { echo "missing $root_file" >&2; exit 1; }
[ -f "$look_file" ] || { echo "missing $look_file" >&2; exit 1; }
cp -a "$root_file" "$root_file.before-animation-presets-$stamp"
cp -a "$look_file" "$look_file.before-animation-presets-$stamp"
mkdir -p "$hypr_dir/generated"
cat > "$hypr_dir/generated/animations.lua" <<'LUAEOF'
-- GENERATED by Quickshell ConfigManager. DO NOT EDIT.
hl.curve("easeOutQuint",   { type = "bezier", points = { {0.23, 1},    {0.32, 1}    } })
hl.curve("easeInOutCubic", { type = "bezier", points = { {0.65, 0.05}, {0.36, 1}    } })
hl.curve("linear",         { type = "bezier", points = { {0, 0},       {1, 1}       } })
hl.curve("almostLinear",   { type = "bezier", points = { {0.5, 0.5},   {0.75, 1}    } })
hl.curve("quick",          { type = "bezier", points = { {0.15, 0},    {0.1, 1}     } })
hl.curve("easy",           { type = "spring", mass = 1, stiffness = 71.2633, dampening = 15.8273644 })

hl.config({ animations = { enabled = true } })
hl.animation({ leaf = "global",        enabled = true, speed = 10,   bezier = "default" })
hl.animation({ leaf = "border",        enabled = true, speed = 5.39, bezier = "easeOutQuint" })
hl.animation({ leaf = "windows",       enabled = true, speed = 4.79, spring = "easy" })
hl.animation({ leaf = "windowsIn",     enabled = true, speed = 4.1,  spring = "easy", style = "popin 87%" })
hl.animation({ leaf = "windowsOut",    enabled = true, speed = 1.49, bezier = "linear", style = "popin 87%" })
hl.animation({ leaf = "fadeIn",        enabled = true, speed = 1.73, bezier = "almostLinear" })
hl.animation({ leaf = "fadeOut",       enabled = true, speed = 1.46, bezier = "almostLinear" })
hl.animation({ leaf = "fade",          enabled = true, speed = 3.03, bezier = "quick" })
hl.animation({ leaf = "layers",        enabled = true, speed = 3.81, bezier = "easeOutQuint" })
hl.animation({ leaf = "layersIn",      enabled = true, speed = 4,    bezier = "easeOutQuint", style = "fade" })
hl.animation({ leaf = "layersOut",     enabled = true, speed = 1.5,  bezier = "linear", style = "fade" })
hl.animation({ leaf = "fadeLayersIn",  enabled = true, speed = 1.79, bezier = "almostLinear" })
hl.animation({ leaf = "fadeLayersOut", enabled = true, speed = 1.39, bezier = "almostLinear" })
hl.animation({ leaf = "workspaces",    enabled = true, speed = 1.94, bezier = "almostLinear", style = "fade" })
hl.animation({ leaf = "workspacesIn",  enabled = true, speed = 1.21, bezier = "almostLinear", style = "slide" })
hl.animation({ leaf = "workspacesOut", enabled = true, speed = 1.94, bezier = "almostLinear", style = "slide" })
hl.animation({ leaf = "zoomFactor",    enabled = true, speed = 7,    bezier = "quick" })
LUAEOF
python3 - "$root_file" "$look_file" <<'PY2'
from pathlib import Path
import re, sys
root = Path(sys.argv[1])
look = Path(sys.argv[2])

# Manager-owned animation config must load AFTER user/look.lua so the
# generated preset is the final authority, including Off.
r = root.read_text()
r = re.sub(r'^\s*require\(["\']generated[./]animations["\']\)\s*\n?', '', r, flags=re.M)
anchor = 'require("user.look")'
if anchor not in r:
    raise SystemExit('require("user.look") not found in hyprland.lua')
r = r.replace(anchor, anchor + '\nrequire("generated.animations")', 1)
root.write_text(r)

s = look.read_text()
# Remove the old leaf/curve block when present.
start = s.find('-- Default curves and animations')
if start >= 0:
    pat = re.compile(r'^hl\.animation\(\{ leaf = "zoomFactor".*?\n', re.M)
    m = pat.search(s, start)
    if not m:
        raise SystemExit('animation block end not found; restore backups and migrate by hand')
    s = s[:start] + '-- Animations are manager-owned in generated/animations.lua.\n' + s[m.end():]

# Remove user/look.lua's animations.enabled assignment. Leaving it here
# would override the generated Off preset because user/look is loaded later
# in older migrated configs.
s, count = re.subn(
    r'\n\s*animations\s*=\s*\{\s*enabled\s*=\s*true,?\s*\},?',
    '', s, count=1, flags=re.S)
look.write_text(s)
PY2
echo "animation ownership migrated"
echo "backups: $root_file.before-animation-presets-$stamp and $look_file.before-animation-presets-$stamp"
echo "Open Settings > Hyprland, choose Smooth, and Apply to generate animations.lua."
