#!/usr/bin/env python3
"""Write the runtime CAVA profile used by Quickshell Music."""

from __future__ import annotations

import argparse
from pathlib import Path


def clamp(value: int, low: int, high: int) -> int:
    return max(low, min(high, value))


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("output")
    parser.add_argument("--bars", type=int, default=32)
    parser.add_argument("--source", choices=("mpd", "system"), default="mpd")
    parser.add_argument("--framerate", type=int, default=60)
    parser.add_argument("--sensitivity", type=int, default=100)
    parser.add_argument("--autosens", type=int, default=1)
    parser.add_argument("--lower", type=int, default=50)
    parser.add_argument("--higher", type=int, default=10000)
    parser.add_argument("--sleep", type=int, default=0)
    parser.add_argument("--reverse", type=int, default=0)
    parser.add_argument("--noise", type=int, default=77)
    args = parser.parse_args()

    bars = clamp(args.bars, 8, 96)
    framerate = clamp(args.framerate, 15, 144)
    sensitivity = clamp(args.sensitivity, 10, 300)
    autosens = clamp(args.autosens, 0, 2)
    lower = clamp(args.lower, 20, 1000)
    higher = clamp(args.higher, max(lower + 100, 1000), 22000)
    sleep_timer = clamp(args.sleep, 0, 60)
    reverse = 1 if args.reverse else 0
    noise = clamp(args.noise, 0, 100)
    source = "mpd.PipeWire" if args.source == "mpd" else "auto"

    text = f"""# Generated by Quickshell. Edit through Settings -> Music.
[general]
bars = {bars}
framerate = {framerate}
sensitivity = {sensitivity}
autosens = {autosens}
lower_cutoff_freq = {lower}
higher_cutoff_freq = {higher}
sleep_timer = {sleep_timer}

[input]
method = pipewire
source = {source}
sample_rate = 48000
sample_bits = 16
active = 1
remix = 1
virtual = 1

[output]
method = raw
channels = mono
mono_option = average
reverse = {reverse}
data_format = ascii
ascii_max_range = 1000
bar_delimiter = 59
frame_delimiter = 10

[smoothing]
monstercat = 0
waves = 0
noise_reduction = {noise}

[eq]
1 = 1
2 = 1
3 = 1
4 = 1
5 = 1
"""

    output = Path(args.output)
    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(text, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
